### ISSUE TITLE
AttributeError: 'EMA' object has no attribute 'defaults'`

### ISSUE THREAD

**Issue by timerobin** [sangyun884/blur-diffusion#3]
Hello , thank you for the code.
I get a AttributeError when i want to train the model:
`Traceback (most recent call last):
  File "main.py", line 292, in <module>
    optimizer.zero_grad()
  File "/home/extradisk/miniconda3/envs/sr3/lib/python3.8/site-packages/torch/optim/optimizer.py", line 231, in zero_grad
    foreach = self.defaults.get('foreach', False)
AttributeError: 'EMA' object has no attribute 'defaults'`
Could you help me with this bug ?

**Comment by YunanWu2168** [comment]
Hi,

I wonder if you solved this problem because I have the same issue.

Best,

**Comment by sangyun884** [comment]
https://github.com/sangyun884/fast-ode/blob/master/EMA.py

Try this code instead, and let me know if it works.

**Comment by GaoTianWL** [comment]
File "E:\anaconda\envs\torch\lib\site-packages\torch\utils\data\sampler.py", line 225, in __init__
    raise ValueError("batch_size should be a positive integer value, "
ValueError: batch_size should be a positive integer value, but got batch_size=0

**Comment by DaddyWesker** [comment]
> https://github.com/sangyun884/fast-ode/blob/master/EMA.py
> 
> Try this code instead, and let me know if it works.

Unfortunately with your code I've got
`AttributeError: 'EMA' object has no attribute '_optimizer_step_pre_hooks'. Did you mean: '_optimizer_step_code'?`

**Comment by ArghyaPal** [comment]
> > https://github.com/sangyun884/fast-ode/blob/master/EMA.py
> > Try this code instead, and let me know if it works.
> 
> Unfortunately with your code I've got `AttributeError: 'EMA' object has no attribute '_optimizer_step_pre_hooks'. Did you mean: '_optimizer_step_code'?`

Any solution to this problem?

**Comment by sangyun884** [comment]
Can you try PyTorch version of 1.11.0 or higher?

**Comment by Kimyuhwanpeter** [comment]
@ArghyaPal, @sangyun884, @DaddyWesker, @YunanWu2168  Just add the code in EMA.py

```
class EMA(Optimizer):
    def __init__(self, opt, ema_decay):
        super().__init__(opt.param_groups, opt.defaults) --> try this
        '....to do....'
```

In my case, this occurred when using ema while training in DDP mode. After much trial and error, I found that PyTorch DDP internally references the optimizer's defaults property, so I added it and confirmed that it worked properly.

I hope this helps.

Thanks.
